# ---- Build stage ---------
FROM node:18-slim AS builder
WORKDIR /app


COPY package*.json ./
RUN npm ci


COPY . .
RUN npm run build          # produces static files in /app/dist

# ---- Runtime stage ---------
FROM nginx:alpine


COPY --from=builder /app/dist /usr/share/nginx/html

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
