name: Build and Push Testnet and Mainnet Images

on:
  push:
    branches: [ main ]
  # also allow manual runs
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3

      - name: Docker Hub login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & Push Testnet Image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile_testnet
          push: true
          platforms: linux/amd64
          cache-from: type=gha
          cache-to: type=gha,mode=max
          tags: |
                ratio1/deeploy_ui:testnet          
      - name: Build & Push Mainnet Image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile_mainnet
          push: true
          platforms: linux/amd64
          cache-from: type=gha
          cache-to: type=gha,mode=max
          tags: |
                ratio1/deeploy_ui:mainnet
